//
// Created by Marco on 24/03/2024.
//

#ifndef WOLF3D_MAP_H
#define WOLF3D_MAP_H

#include "defs.h"
#include "tile.h"

Tile maps[MAP_NUMBER][MAP_SIZE * MAP_SIZE] = {
        {
                TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_EMPTY,      TILE_EMPTY,      TILE_EMPTY,      TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_EMPTY,      TILE_EMPTY,      TILE_EMPTY,      TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_EMPTY,      TILE_EMPTY,      TILE_EMPTY,      TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_EMPTY,      TILE_EMPTY,      TILE_EMPTY,      TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_EMPTY,      TILE_EMPTY,      TILE_EMPTY,      TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_EMPTY,      TILE_EMPTY,      TILE_EMPTY,      TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
                TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_WALL_BRICK, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
        }
};

#endif //WOLF3D_MAP_H
