//
// Created by Marco on 24/03/2024.
//

#ifndef WOLF3D_TILE_H
#define WOLF3D_TILE_H

typedef enum {
    TILE_TYPE_WALL,
    TILE_TYPE_ENEMY,
    TILE_TYPE_DROP,
    TILE_TYPE_NONE
} TileType;

typedef enum {
    TILE_STATE_IDLE,
    TILE_STATE_MOVING,
    TILE_STATE_SHOOTING,
    TILE_STATE_DEAD,
    TILE_STATE_NULL,
} TileState;

typedef enum {
    //
    // Every tile has the dark version next to it
    //
    WALL_BLUESTONE1, WALL_BLUESTONE2,
    WALL_BLUESTONE3, WALL_BLUESTONE4,
    WALL_BLUESTONE5, WALL_BLUESTONE6,
    WALL_BLUESTONE7, WALL_BLUESTONE8,
    WALL_BLUESTONE9, WALL_BLUESTONE10,

    WALL_BLUEWALL1, WALL_BLUEWALL2,
    WALL_BLUEWALL3, WALL_BLUEWALL4,
    WALL_BLUEWALL5, WALL_BLUEWALL6,

    WALL_BRICK1, WALL_BRICK2,
    WALL_BRICK3, WALL_BRICK4,
    WALL_BRICK5, WALL_BRICK6,
    WALL_BRICK7, WALL_BRICK8,

    WALL_BROWNSTONE1, WALL_BROWNSTONE2,
    WALL_BROWNSTONE3, WALL_BROWNSTONE4,
    WALL_BROWNSTONE5, WALL_BROWNSTONE6,
    WALL_BROWNSTONE7, WALL_BROWNSTONE8,
    WALL_BROWNSTONE9, WALL_BROWNSTONE10,

    WALL_CAVE1, WALL_CAVE2,
    WALL_CAVE3, WALL_CAVE4,
    WALL_CAVE5, WALL_CAVE6,
    WALL_CAVE7, WALL_CAVE8,

    WALL_DIRTYSTONE1, WALL_DIRTYSTONE2,
    WALL_DIRTYSTONE3, WALL_DIRTYSTONE4,

    WALL_DOOR1, WALL_DOOR2,
    WALL_DOOR3, WALL_DOOR4,
    WALL_DOOR5, WALL_DOOR6,
    WALL_DOOR7, WALL_DOOR8,

    WALL_DOORSLOT1, WALL_DOORSLOT2,

    WALL_GREYBRICK1, WALL_GREYBRICK2,
    WALL_GREYBRICK3, WALL_GREYBRICK4,
    WALL_GREYBRICK5, WALL_GREYBRICK6,
    WALL_GREYBRICK7, WALL_GREYBRICK8,
    WALL_GREYBRICK9, WALL_GREYBRICK10,

    WALL_HELL1, WALL_HELL2,

    WALL_MARBLE1, WALL_MARBLE2,
    WALL_MARBLE3, WALL_MARBLE4,
    WALL_MARBLE5, WALL_MARBLE6,

    WALL_METAL1, WALL_METAL2,
    WALL_METAL3, WALL_METAL4,

    WALL_PURPLE1, WALL_PURPLE2,
    WALL_PURPLE3, WALL_PURPLE4,

    WALL_PURPLEBRICK1, WALL_PURPLEBRICK2,

    WALL_SGLASS1, WALL_SGLASS2,

    WALL_STONE1, WALL_STONE2,
    WALL_STONE3, WALL_STONE4,
    WALL_STONE5, WALL_STONE6,
    WALL_STONE7, WALL_STONE8,
    WALL_STONE9, WALL_STONE10,
    WALL_STONE11, WALL_STONE12,
    WALL_STONE13, WALL_STONE14,
    WALL_STONE15, WALL_STONE16,
    WALL_STONE17, WALL_STONE18,
    WALL_STONE19, WALL_STONE20,
    WALL_STONE21, WALL_STONE22,
    WALL_STONE23, WALL_STONE24,
    WALL_STONE25, WALL_STONE26,

    WALL_WOOD1, WALL_WOOD2,
    WALL_WOOD3, WALL_WOOD4,
    WALL_WOOD5, WALL_WOOD6,
    WALL_WOOD7, WALL_WOOD8,
    WALL_WOOD9, WALL_WOOD10,

    //
    // These tiles have no dark version
    //
    WALL_ELEVATOR1,
    WALL_ELEVATOR2, WALL_ELEVATOR3,
    WALL_ELEVATOR4,
    WALL_ELEVATOR5,
    WALL_NULL,
} Wall;

#define N_WALL                      (WALL_NULL)
#define START_NO_DARK_VERIONS_WALL  (WALL_ELEVATOR1)

const char* wallToString(Wall wall);

typedef struct {
    TileType    type;
    Wall        wall;
    TileState   state;
    float       movedPerc;
} Tile;

#define TILE_MT     { TILE_TYPE_NONE, WALL_NULL, TILE_STATE_NULL, 0 }

#define WLL_BLST_1  { TILE_TYPE_WALL, WALL_BLUESTONE1, TILE_STATE_IDLE, 0 }
#define WLL_BLST_3  { TILE_TYPE_WALL, WALL_BLUESTONE3, TILE_STATE_IDLE, 0 }
#define WLL_BLST_5  { TILE_TYPE_WALL, WALL_BLUESTONE5, TILE_STATE_IDLE, 0 }
#define WLL_BLST_7  { TILE_TYPE_WALL, WALL_BLUESTONE7, TILE_STATE_IDLE, 0 }
#define WLL_BLST_9  { TILE_TYPE_WALL, WALL_BLUESTONE9, TILE_STATE_IDLE, 0 }

#define WLL_BLWL_1  { TILE_TYPE_WALL, WALL_BLUEWALL1, TILE_STATE_IDLE, 0 }
#define WLL_BLWL_3  { TILE_TYPE_WALL, WALL_BLUEWALL3, TILE_STATE_IDLE, 0 }
#define WLL_BLWL_5  { TILE_TYPE_WALL, WALL_BLUEWALL5, TILE_STATE_IDLE, 0 }

#define WLL_BRCK_1  { TILE_TYPE_WALL, WALL_BRICK1, TILE_STATE_IDLE, 0 }
#define WLL_BRCK_3  { TILE_TYPE_WALL, WALL_BRICK3, TILE_STATE_IDLE, 0 }
#define WLL_BRCK_5  { TILE_TYPE_WALL, WALL_BRICK5, TILE_STATE_IDLE, 0 }
#define WLL_BRCK_7  { TILE_TYPE_WALL, WALL_BRICK7, TILE_STATE_IDLE, 0 }

#define WLL_BRST_1  { TILE_TYPE_WALL, WALL_BROWNSTONE1, TILE_STATE_IDLE, 0 }
#define WLL_BRST_3  { TILE_TYPE_WALL, WALL_BROWNSTONE3, TILE_STATE_IDLE, 0 }
#define WLL_BRST_5  { TILE_TYPE_WALL, WALL_BROWNSTONE5, TILE_STATE_IDLE, 0 }
#define WLL_BRST_7  { TILE_TYPE_WALL, WALL_BROWNSTONE7, TILE_STATE_IDLE, 0 }
#define WLL_BRST_9  { TILE_TYPE_WALL, WALL_BROWNSTONE9, TILE_STATE_IDLE, 0 }

#define WLL_CAVE_1  { TILE_TYPE_WALL, WALL_CAVE1, TILE_STATE_IDLE, 0 }
#define WLL_CAVE_3  { TILE_TYPE_WALL, WALL_CAVE3, TILE_STATE_IDLE, 0 }
#define WLL_CAVE_5  { TILE_TYPE_WALL, WALL_CAVE5, TILE_STATE_IDLE, 0 }
#define WLL_CAVE_7  { TILE_TYPE_WALL, WALL_CAVE7, TILE_STATE_IDLE, 0 }

#define WLL_DRST_1  { TILE_TYPE_WALL, WALL_DIRTYSTONE1, TILE_STATE_IDLE, 0 }
#define WLL_DRST_3  { TILE_TYPE_WALL, WALL_DIRTYSTONE3, TILE_STATE_IDLE, 0 }

#define WLL_DR_1    { TILE_TYPE_WALL, WALL_DOOR1, TILE_STATE_IDLE, 0 }
#define WLL_DR_3    { TILE_TYPE_WALL, WALL_DOOR3, TILE_STATE_IDLE, 0 }
#define WLL_DR_5    { TILE_TYPE_WALL, WALL_DOOR5, TILE_STATE_IDLE, 0 }
#define WLL_DR_7    { TILE_TYPE_WALL, WALL_DOOR7, TILE_STATE_IDLE, 0 }

#define WLL_DRSLT_1 { TILE_TYPE_WALL, WALL_DOORSLOT1, TILE_STATE_IDLE, 0 }

#define WLL_GRBR_1  { TILE_TYPE_WALL, WALL_GREYBRICK1, TILE_STATE_IDLE, 0 }
#define WLL_GRBR_3  { TILE_TYPE_WALL, WALL_GREYBRICK3, TILE_STATE_IDLE, 0 }
#define WLL_GRBR_5  { TILE_TYPE_WALL, WALL_GREYBRICK5, TILE_STATE_IDLE, 0 }
#define WLL_GRBR_7  { TILE_TYPE_WALL, WALL_GREYBRICK7, TILE_STATE_IDLE, 0 }
#define WLL_GRBR_9  { TILE_TYPE_WALL, WALL_GREYBRICK9, TILE_STATE_IDLE, 0 }

#define WLL_HLL_1   { TILE_TYPE_WALL, WALL_HELL1, TILE_STATE_IDLE, 0 }

#define WLL_MRBL_1  { TILE_TYPE_WALL, WALL_MARBLE1, TILE_STATE_IDLE, 0 }
#define WLL_MRBL_3  { TILE_TYPE_WALL, WALL_MARBLE3, TILE_STATE_IDLE, 0 }
#define WLL_MRBL_5  { TILE_TYPE_WALL, WALL_MARBLE5, TILE_STATE_IDLE, 0 }

#define WLL_MTL_1   { TILE_TYPE_WALL, WALL_METAL1, TILE_STATE_IDLE, 0 }
#define WLL_MTL_3   { TILE_TYPE_WALL, WALL_METAL3, TILE_STATE_IDLE, 0 }

#define WLL_PRPL_1  { TILE_TYPE_WALL, WALL_PURPLE1, TILE_STATE_IDLE, 0 }
#define WLL_PRPL_3  { TILE_TYPE_WALL, WALL_PURPLE3, TILE_STATE_IDLE, 0 }

#define WLL_PRPLBRK_1 { TILE_TYPE_WALL, WALL_PURPLEBRICK1, TILE_STATE_IDLE, 0 }

#define WLL_SGLSS_1 { TILE_TYPE_WALL, WALL_SGLASS1, TILE_STATE_IDLE, 0 }

#define WLL_STN_1   { TILE_TYPE_WALL, WALL_STONE1, TILE_STATE_IDLE, 0 }
#define WLL_STN_3   { TILE_TYPE_WALL, WALL_STONE3, TILE_STATE_IDLE, 0 }
#define WLL_STN_5   { TILE_TYPE_WALL, WALL_STONE5, TILE_STATE_IDLE, 0 }
#define WLL_STN_7   { TILE_TYPE_WALL, WALL_STONE7, TILE_STATE_IDLE, 0 }
#define WLL_STN_9   { TILE_TYPE_WALL, WALL_STONE9, TILE_STATE_IDLE, 0 }
#define WLL_STN_11  { TILE_TYPE_WALL, WALL_STONE11, TILE_STATE_IDLE, 0 }
#define WLL_STN_13  { TILE_TYPE_WALL, WALL_STONE13, TILE_STATE_IDLE, 0 }
#define WLL_STN_15  { TILE_TYPE_WALL, WALL_STONE15, TILE_STATE_IDLE, 0 }
#define WLL_STN_17  { TILE_TYPE_WALL, WALL_STONE17, TILE_STATE_IDLE, 0 }
#define WLL_STN_19  { TILE_TYPE_WALL, WALL_STONE19, TILE_STATE_IDLE, 0 }
#define WLL_STN_21  { TILE_TYPE_WALL, WALL_STONE21, TILE_STATE_IDLE, 0 }
#define WLL_STN_23  { TILE_TYPE_WALL, WALL_STONE23, TILE_STATE_IDLE, 0 }
#define WLL_STN_25  { TILE_TYPE_WALL, WALL_STONE25, TILE_STATE_IDLE, 0 }

#define WLL_WD_1    { TILE_TYPE_WALL, WALL_WOOD1, TILE_STATE_IDLE, 0 }
#define WLL_WD_3    { TILE_TYPE_WALL, WALL_WOOD3, TILE_STATE_IDLE, 0 }
#define WLL_WD_5    { TILE_TYPE_WALL, WALL_WOOD5, TILE_STATE_IDLE, 0 }
#define WLL_WD_7    { TILE_TYPE_WALL, WALL_WOOD7, TILE_STATE_IDLE, 0 }
#define WLL_WD_9    { TILE_TYPE_WALL, WALL_WOOD9, TILE_STATE_IDLE, 0 }

#endif //WOLF3D_TILE_H
